[package]
name = "rust-workspace"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1.18.1", features = ["full"] }

[dev-dependencies]

[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["user-hooks"] # Store all hooks in the .cargo-husky/hooks directory
