name: gh-pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Workspace cache
        uses: ./.github/actions/workspace-cache

      - name: Install rust
        run: |
          sudo apt-get update
          sudo apt-get install libfontconfig1-dev
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Install project dependencies
        run: cargo install --path . --force

      - name: Build and deploy rustdoc
        uses: ./.github/actions/deploy-pages
